services:
  mariadb:
    image: mariadb:10.9.2
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: food-reservation
    ports:
      - "3306:3306"
  app:
    profiles:
      - app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JEP: ${JEP}
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/food-reservation
