/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.foodlab.foodReservation;

import org.junit.jupiter.api.Test;

class FoodReservationApplicationTests {

    @Test
    void test() {}
}
