name: Build push deploy

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'document/**'
  push:
    paths-ignore:
      - 'document/**'

env:
  DOCKERHUB_USER_NAME: oldrabbit736
  IMAGE_NAME: oldrabbit736/food-reservation-app:0.0.${{ github.run_number }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build --scan

      - name: Build container image
        run: docker build app/ -t ${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push to container registry
        run: docker push ${{ env.IMAGE_NAME }}

      # TODO
#      - name: Deploy to production server
