name: Test

on:
  pull_request:
    paths-ignore:
      - 'document/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # workflow summary 에 build scan 결과 링크 등 유저 인터페이스를 추가하기 위한 action
      # https://github.com/marketplace/actions/gradle-build-action#build-scans
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # docker compose 이용하여 test 수행에 필요한 외부 서비스 실행
      - name: Set up test environment
        run: sh script/test-ci.sh

      # build task 를 수행하는 과정에서 test, integration test task 실행
      - name: build
        run: ./gradlew build --scan
